### ISSUE TITLE
node:internal/errors:490

### ISSUE THREAD

**Issue by JayroJones** [agg23/Analogue-Pocket-Image-Process#1]
Maybe I'm just stupid, but my Node.js is fully updated, and I still get this error when trying to use it. Any help is appreciated.

![wtf](https://user-images.githubusercontent.com/86807949/230126780-265812ee-6ef1-4e0e-8394-c7796f379286.jpg)

_(Also, I didn't see anywhere in the ReadMe where Node js was a prerequisite, so that would be useful information for new users.)_

**Comment by agg23** [comment]
You need to install dependencies. The standard process for cloning Node projects is to run `npm i`, which installs all dependencies.

My apologies for the confusion. I only really intended this tool to be for devs, but I'm glad others are using it. As an end user, I recommend using [Pocket Sync](https://github.com/neil-morrison44/pocket-sync) to update the platform images.

**Comment by JayroJones** [comment]
Thank you, got it all working now. :)

(I'm trying to make my own image pack.)
